# -*- coding: utf-8 -*-
"""
从case_study_summary.json重新生成所有IDF（修复v23.2兼容性），然后跑仿真
"""
import os, sys, json, subprocess, re, numpy as np
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

EP_DIR = r"C:\Users\chunge\.gemini\antigravity\scratch\EnergyPlus-23.2\EnergyPlus-23.2.0-7636e6b3e9-Windows-x86_64"
EP_EXE = os.path.join(EP_DIR, "energyplus.exe")
EPW_FILE = os.path.join(EP_DIR, "WeatherData", "USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw")
BASE = r"C:\Users\chunge\.gemini\antigravity\scratch\floorplan_segmentation"
CASE_DIR = os.path.join(BASE, "output_paper", "case_study")

sys.path.insert(0, BASE)

CASES = [
    "case_1_verify_0_333",
    "case_2_verify_1_1654",
    "case_3_verify_2_5559",
    "case_4_verify_3_3015",
    "case_5_verify_4_5748",
]

import datetime

def generate_idf_v23(walls, windows, doors, rooms, scale=0.02, wall_height=2.8, output_path='model.idf'):
    """生成EnergyPlus v23.2兼容的IDF"""
    L = []
    def add(s): L.append(s)
    
    add("!- Generated by FloorPlan2BIM Pipeline (v23.2 compatible)")
    add(f"!- Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")
    add(f"!- Walls: {len(walls)}, Windows: {len(windows)}, Doors: {len(doors)}, Rooms: {len(rooms)}")
    add(""); add("Version, 23.2;"); add("")
    
    add("SimulationControl,")
    add("    No,  No,  No,  Yes,  Yes;")
    add("")
    
    add("Building,")
    add("    AutoBIM Building, 0, City, 0.04, 0.4, FullInteriorAndExterior, 25, 6;")
    add(""); add("Timestep, 4;"); add("")
    
    # RunPeriod - v23.2: day_of_week_for_start_day 用空值
    add("RunPeriod,")
    add("    AnnualRun, 1, 1, , 12, 31, , , Yes, Yes, No, Yes, Yes;")
    add("")
    
    add("GlobalGeometryRules, UpperLeftCorner, Counterclockwise, Relative;")
    add("")
    
    # Materials
    add("!- ============ MATERIALS ============")
    add("Material, Concrete200, MediumRough, 0.200, 1.740, 2400, 880, 0.9, 0.6, 0.6;")
    add("Material, Insulation50, MediumSmooth, 0.050, 0.040, 30, 1400, 0.9, 0.5, 0.5;")
    add("Material, Plaster20, Smooth, 0.020, 0.810, 1600, 1050, 0.9, 0.4, 0.4;")
    add("")
    add("Construction, ExteriorWall, Plaster20, Insulation50, Concrete200, Plaster20;")
    add("Construction, InteriorWall, Plaster20, Concrete200, Plaster20;")
    add("WindowMaterial:SimpleGlazingSystem, SimpleWindow, 2.700, 0.400, 0.600;")
    add("Construction, WindowConst, SimpleWindow;")
    add("Construction, Floor, Concrete200;")
    add("Construction, Roof, Plaster20, Insulation50, Concrete200;")
    add("")
    
    # Schedule Type Limits
    add("!- ============ SCHEDULES ============")
    add("ScheduleTypeLimits, Fraction, 0, 1, CONTINUOUS;")
    add("ScheduleTypeLimits, ActivityLevel, 0, 500, CONTINUOUS;")
    add("ScheduleTypeLimits, Temperature, -100, 200, CONTINUOUS;")
    add("ScheduleTypeLimits, ControlType, 0, 4, DISCRETE;")
    add("")
    
    # Schedules
    add("Schedule:Compact, OccupancySch, Fraction,")
    add("    Through: 12/31, For: Weekdays,")
    add("    Until: 7:00, 1.0, Until: 9:00, 0.5, Until: 17:00, 0.2, Until: 22:00, 0.8, Until: 24:00, 1.0,")
    add("    For: Weekends Holidays,")
    add("    Until: 9:00, 1.0, Until: 22:00, 0.8, Until: 24:00, 1.0;")
    add("")
    add("Schedule:Compact, LightingSch, Fraction,")
    add("    Through: 12/31, For: AllDays,")
    add("    Until: 7:00, 0.1, Until: 18:00, 0.3, Until: 23:00, 0.8, Until: 24:00, 0.1;")
    add("")
    add("Schedule:Compact, EquipmentSch, Fraction,")
    add("    Through: 12/31, For: AllDays,")
    add("    Until: 7:00, 0.3, Until: 9:00, 0.5, Until: 17:00, 0.3, Until: 22:00, 0.7, Until: 24:00, 0.3;")
    add("")
    add("Schedule:Compact, ActivitySch, ActivityLevel,")
    add("    Through: 12/31, For: AllDays, Until: 24:00, 120.0;")
    add("")
    add("Schedule:Compact, HeatingSP, Temperature,")
    add("    Through: 12/31, For: AllDays, Until: 24:00, 18.0;")
    add("")
    add("Schedule:Compact, CoolingSP, Temperature,")
    add("    Through: 12/31, For: AllDays, Until: 24:00, 26.0;")
    add("")
    add("Schedule:Compact, AlwaysOn, Fraction,")
    add("    Through: 12/31, For: AllDays, Until: 24:00, 1.0;")
    add("")
    add("Schedule:Compact, DualSPControl, ControlType,")
    add("    Through: 12/31, For: AllDays, Until: 24:00, 4;")
    # 4 = DualSetpoint thermostat control type
    add("")
    
    # Zones
    add("!- ============ ZONES ============")
    for r in rooms:
        zn = f"Room_{r['id']}"
        cx = r['center'][0] * scale
        cy = r['center'][1] * scale
        rw = r['width'] * scale / 2
        rh = r['height'] * scale / 2
        h = wall_height
        
        add(f"Zone, {zn}, 0, {cx:.3f}, {cy:.3f}, 0, 1, 1, autocalculate, autocalculate;")
        add("")
        
        # Floor
        add(f"BuildingSurface:Detailed, {zn}_Floor, Floor, Floor, {zn}, , Ground, , NoSun, NoWind, , 4,")
        add(f"    {-rw:.3f},{-rh:.3f},0, {-rw:.3f},{rh:.3f},0, {rw:.3f},{rh:.3f},0, {rw:.3f},{-rh:.3f},0;")
        add("")
        
        # Ceiling
        add(f"BuildingSurface:Detailed, {zn}_Ceiling, Ceiling, Roof, {zn}, , Outdoors, , SunExposed, WindExposed, , 4,")
        add(f"    {-rw:.3f},{-rh:.3f},{h}, {rw:.3f},{-rh:.3f},{h}, {rw:.3f},{rh:.3f},{h}, {-rw:.3f},{rh:.3f},{h};")
        add("")
        
        # 4 walls
        for wname, verts in [
            ('North', f"{-rw:.3f},{rh:.3f},{h}, {rw:.3f},{rh:.3f},{h}, {rw:.3f},{rh:.3f},0, {-rw:.3f},{rh:.3f},0"),
            ('East',  f"{rw:.3f},{rh:.3f},{h}, {rw:.3f},{-rh:.3f},{h}, {rw:.3f},{-rh:.3f},0, {rw:.3f},{rh:.3f},0"),
            ('South', f"{rw:.3f},{-rh:.3f},{h}, {-rw:.3f},{-rh:.3f},{h}, {-rw:.3f},{-rh:.3f},0, {rw:.3f},{-rh:.3f},0"),
            ('West',  f"{-rw:.3f},{-rh:.3f},{h}, {-rw:.3f},{rh:.3f},{h}, {-rw:.3f},{rh:.3f},0, {-rw:.3f},{-rh:.3f},0"),
        ]:
            add(f"BuildingSurface:Detailed, {zn}_Wall_{wname}, Wall, ExteriorWall, {zn}, , Outdoors, , SunExposed, WindExposed, , 4,")
            add(f"    {verts};")
            add("")
        
        # Internal loads
        add(f"People, {zn}_People, {zn}, OccupancySch, Area/Person, , , 30, 0.3, autocalculate, ActivitySch;")
        add(f"Lights, {zn}_Lights, {zn}, LightingSch, Watts/Area, , 8.0, , 0, 0.4, 0.2;")
        add(f"ElectricEquipment, {zn}_Equip, {zn}, EquipmentSch, Watts/Area, , 10.0, , 0, 0.3, 0;")
        add("")
        
        # HVAC
        add(f"ZoneHVAC:EquipmentConnections, {zn}, {zn}_EquipList, {zn}_SupplyInlet, , {zn}_ZoneAirNode, {zn}_ReturnAirNode;")
        add("")
        add(f"ZoneHVAC:EquipmentList, {zn}_EquipList, SequentialLoad, ZoneHVAC:IdealLoadsAirSystem, {zn}_IdealHVAC, 1, 1, , ;")
        add("")
        add(f"ZoneHVAC:IdealLoadsAirSystem, {zn}_IdealHVAC, AlwaysOn, {zn}_SupplyInlet, , , 50, 13, 0.0156, 0.0077;")
        add("")
        add(f"ZoneControl:Thermostat, {zn}_Thermostat, {zn}, DualSPControl, ThermostatSetpoint:DualSetpoint, {zn}_DualSP;")
        add(f"ThermostatSetpoint:DualSetpoint, {zn}_DualSP, HeatingSP, CoolingSP;")
        add("")
    
    # Output
    add("!- ============ OUTPUT ============")
    add("Output:Variable,*,Zone Ideal Loads Supply Air Total Heating Energy,Monthly;")
    add("Output:Variable,*,Zone Ideal Loads Supply Air Total Cooling Energy,Monthly;")
    add("Output:Variable,*,Zone Mean Air Temperature,Monthly;")
    add("OutputControl:Table:Style, HTML;")
    add("Output:Table:SummaryReports, AllSummary;")
    add("")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L))
    
    return len(rooms)


# === Step 1: 从 mask 重新提取几何并生成 IDF ===
from mask_to_ifc import extract_wall_segments, extract_openings, extract_rooms
import cv2

for case_name in CASES:
    case_path = os.path.join(CASE_DIR, case_name)
    
    # 找到分割 mask（pred_mask.npy 或 segmentation_mask.npy）
    mask_candidates = [
        os.path.join(case_path, "pred_mask.npy"),
        os.path.join(case_path, "segmentation_mask.npy"),
        os.path.join(case_path, "mask.npy"),
    ]
    # 也试试从 png 恢复
    png_candidates = [
        os.path.join(case_path, "pred_colored.png"),
        os.path.join(case_path, "prediction.png"),
    ]
    
    mask = None
    # 先试 npy
    for mp in [os.path.join(case_path, f) for f in ['pred_mask.npy', 'segmentation_mask.npy', 'mask.npy']]:
        if os.path.isfile(mp):
            mask = np.load(mp)
            print(f"{case_name}: loaded mask from {os.path.basename(mp)}, shape={mask.shape}")
            break
    
    # 试 PNG (灰度值需要 remap 到 0-3)
    if mask is None:
        for mp in [os.path.join(case_path, f) for f in ['segmentation_mask.png', 'pred_colored.png', 'prediction.png']]:
            if os.path.isfile(mp):
                import cv2
                raw = cv2.imread(mp, cv2.IMREAD_GRAYSCALE)
                vals = sorted(np.unique(raw))
                mask = np.zeros_like(raw)
                for i, v in enumerate(vals):
                    mask[raw == v] = i
                print(f"{case_name}: loaded mask from {os.path.basename(mp)}, shape={mask.shape}, classes={len(vals)}")
                break
    
    if mask is None:
        files = [f for f in os.listdir(case_path) if f.endswith(('.npy', '.png'))]
        print(f"{case_name}: ❌ No mask found. Files: {files}")
        continue
    
    # 提取几何
    walls = extract_wall_segments(mask)
    windows = extract_openings(mask, 2, walls)
    doors = extract_openings(mask, 3, walls)
    rooms = extract_rooms(mask)
    
    print(f"  Geometry: {len(walls)} walls, {len(windows)} windows, {len(doors)} doors, {len(rooms)} rooms")
    
    # 生成新 IDF
    idf_path = os.path.join(case_path, "model.idf")
    n = generate_idf_v23(walls, windows, doors, rooms, scale=0.02, output_path=idf_path)
    print(f"  ✅ Generated IDF with {n} zones")

# === Step 2: 跑仿真 ===
print(f"\n{'='*60}")
print("开始 EnergyPlus v23.2 仿真 (Chicago TMY3)")
print(f"{'='*60}")

results = []
for ci, case_name in enumerate(CASES):
    case_path = os.path.join(CASE_DIR, case_name)
    idf_path = os.path.join(case_path, "model.idf")
    if not os.path.isfile(idf_path):
        results.append({"case": case_name, "status": "SKIP"})
        continue
    
    out_dir = os.path.join(case_path, "ep_output")
    os.makedirs(out_dir, exist_ok=True)
    for f in os.listdir(out_dir):
        try: os.remove(os.path.join(out_dir, f))
        except: pass
    
    print(f"\n[{ci+1}/5] {case_name}...")
    cmd = [EP_EXE, "-w", EPW_FILE, "-d", out_dir, "-r", idf_path]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    
    if proc.returncode != 0:
        err_file = os.path.join(out_dir, "eplusout.err")
        print(f"  ❌ Failed (exit={proc.returncode})")
        if os.path.isfile(err_file):
            with open(err_file, 'r') as f:
                for line in f:
                    ll = line.strip()
                    if 'Severe' in ll or 'Fatal' in ll:
                        print(f"    {ll}")
        results.append({"case": case_name, "status": "FAILED"})
        continue
    
    energy = {"case": case_name, "status": "OK"}
    
    # Parse results
    end_file = os.path.join(out_dir, "eplusout.end")
    if os.path.isfile(end_file):
        with open(end_file, 'r') as f:
            end_txt = f.read().strip()
            print(f"  {end_txt}")
            if 'Successfully' in end_txt:
                energy["sim_ok"] = True
    
    tbl_file = os.path.join(out_dir, "eplustbl.htm")
    if os.path.isfile(tbl_file):
        with open(tbl_file, 'r', encoding='utf-8', errors='ignore') as f:
            htm = f.read()
        for pat, key in [
            (r'Total Site Energy</td>.*?<td.*?>([0-9.]+)</td>', 'total_site_GJ'),
            (r'Total Site Energy per Total Building Area</td>.*?<td.*?>([0-9.]+)</td>', 'EUI_MJ_m2'),
            (r'Net Site Energy per Conditioned Building Area</td>.*?<td.*?>([0-9.]+)</td>', 'net_EUI_MJ_m2'),
            (r'Total Building Area</td>.*?<td.*?>([0-9.]+)</td>', 'floor_area_m2'),
        ]:
            m = re.search(pat, htm, re.DOTALL)
            if m:
                energy[key] = float(m.group(1))
        if 'EUI_MJ_m2' in energy:
            energy['EUI_kWh_m2'] = round(energy['EUI_MJ_m2'] / 3.6, 1)
    
    err_file = os.path.join(out_dir, "eplusout.err")
    if os.path.isfile(err_file):
        with open(err_file, 'r') as f:
            err_text = f.read()
        energy["warnings"] = err_text.count(' Warning;')
        energy["severes"] = err_text.count(' Severe')
    
    results.append(energy)
    eui = energy.get('EUI_kWh_m2', '?')
    area = energy.get('floor_area_m2', '?')
    print(f"  ✅ Area={area}m², EUI={eui} kWh/m²/yr")

# === Summary ===
print(f"\n\n{'='*60}")
print("📊 EnergyPlus 年仿真结果")
print(f"{'='*60}")
print(f"{'Case':<30} {'Area(m²)':<10} {'EUI(kWh/m²)':<14} {'Total(GJ)':<12}")
print("-" * 66)
for r in results:
    e = "✅" if r.get("status") == "OK" else "❌"
    area = r.get('floor_area_m2', '-')
    eui = r.get('EUI_kWh_m2', '-')
    total = r.get('total_site_GJ', '-')
    print(f"{e} {r['case']:<28} {str(area):<10} {str(eui):<14} {str(total):<12}")

with open(os.path.join(CASE_DIR, "ep_simulation_results.json"), 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)
print(f"\n✅ 结果已保存")
